In [1]:
import numpy as np
from sklearn.cluster import DBSCAN

In [2]:
area = np.array([120, 145, 80, 160, 200, 90, 110, 130, 180, 160])
valor = np.array([300, 450, 550, 600, 350, 420, 550, 780, 360, 575])
dist_praia = np.array([15, 15, 8, 25, 12, 15, 22, 8, 5, 14])

In [4]:
dados = np.column_stack((area, dist_praia, valor))

In [5]:
dbscan = DBSCAN(eps=20, min_samples=2)
clusters = dbscan.fit_predict(dados)

In [6]:
dados_com_clusters = np.column_stack((dados, clusters))

In [7]:
print("Dados com Clusters:")
print(dados_com_clusters)

Dados com Clusters:
[[120  15 300  -1]
 [145  15 450  -1]
 [ 80   8 550  -1]
 [160  25 600  -1]
 [200  12 350  -1]
 [ 90  15 420  -1]
 [110  22 550  -1]
 [130   8 780  -1]
 [180   5 360  -1]
 [160  14 575  -1]]


In [8]:
num_clusters = len(set(clusters)) - (1 if -1 in clusters else 0)  
for i in range(num_clusters):
    cluster_indices = np.where(clusters == i)[0]
    valor_medio = np.mean(valor[cluster_indices])
    print(f"Grupo {i}: Valor Médio = {valor_medio}")