In [1]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder

In [2]:
data = {
    'Teor Alcoólico': [3, 4, 5, 6],
    'Acidez': ['muito', 'pouco', 'médio', 'baixo'],
    'pH': [4.3, 2.8, 4.2, 3.9]
}

df = pd.DataFrame(data)

In [3]:
le = LabelEncoder()
df['Acidez'] = le.fit_transform(df['Acidez'])

X = df.values

In [4]:
print("DataFrame:")
print(df)

print("\nMatriz numpy:")
print(X)

DataFrame:
   Teor Alcoólico  Acidez   pH
0               3       1  4.3
1               4       3  2.8
2               5       2  4.2
3               6       0  3.9

Matriz numpy:
[[3.  1.  4.3]
 [4.  3.  2.8]
 [5.  2.  4.2]
 [6.  0.  3.9]]
